[package]
name = "ubpkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocative = "0.3.3"
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
color-eyre = "0.6.2"
decompress = "0.6.0"
directories = "5.0.1"
include_dir = "0.7.3"
regex = "1.10.3"
starlark = "0.12.0"
tempdir = "0.3.7"
thiserror = "1.0.57"
ureq = "2.9.6"
vsort = "0.2.0"
