[package]
name = "ubpkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocative = "0.3.3"
anyhow = "1.0.86"
clap = { version = "4.5.15", features = ["derive"] }
color-eyre = "0.6.3"
decompress = { version = "0.6.0", default-features = false, features = ["targz", "zip", "gz"] }
directories = "5.0.1"
include_dir = "0.7.4"
regex = "1.10.6"
starlark = "0.12.0"
tempdir = "0.3.7"
thiserror = "1.0.63"
ureq = "2.9.7"
vsort = "0.2.0"
