[package]
name = "ubpkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocative = "0.3.4"
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
color-eyre = "0.6.3"
decompress = { version = "0.6.0", default-features = false, features = ["targz", "zip", "gz", "tarxz"] }
directories = "5.0.1"
include_dir = "0.7.4"
regex = "1.11.1"
starlark = "0.13.0"
tempdir = "0.3.7"
thiserror = "2.0.7"
ureq = "2.12.1"
vsort = "0.2.0"
