[package]
name = "ubpkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocative = "0.3.3"
anyhow = "1.0.80"
include_dir = "0.7.3"
starlark = "0.12.0"
vsort = "0.2.0"
